-- ClientMain (LocalScript)
-- Startet alle Client-Module. Sie reagieren selbst auf den aktuellen Modus (Hub, Free-for-All, Drop).

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Shared")
local InputActions = require(Shared.InputActions)
local PlayerSettings = require(Shared.PlayerSettings)
local Movement = require(Shared.Movement)
local WeaponClient = require(Shared.WeaponClient)
local CharacterPose = require(Shared.CharacterPose)
local HUD = require(Shared.HUD)
local Notifications = require(Shared.Notifications)
local GameMenu = require(Shared.GameMenu)
local AbilityClient = require(Shared.AbilityClient)
local Glide = require(script.Parent:WaitForChild("Glide"))
local Spectator = require(script.Parent:WaitForChild("Spectator"))
local AgentSelect = require(script.Parent:WaitForChild("AgentSelect"))
local AdminPanel = require(script.Parent:WaitForChild("AdminPanel"))
local SideMenu = require(script.Parent:WaitForChild("SideMenu"))
local Scoreboard = require(script.Parent:WaitForChild("Scoreboard"))
local Downed = require(script.Parent:WaitForChild("Downed"))
local ObjectivePrompt = require(script.Parent:WaitForChild("ObjectivePrompt"))
local Pings = require(script.Parent:WaitForChild("Pings"))
local MatchSummary = require(script.Parent:WaitForChild("MatchSummary"))
local HubLineup = require(script.Parent:WaitForChild("HubLineup"))
local Nametags = require(script.Parent:WaitForChild("Nametags"))
local MapVote = require(script.Parent:WaitForChild("MapVote"))
local MapAtmosphere = require(script.Parent:WaitForChild("MapAtmosphere"))
local GraphicsQuality = require(script.Parent:WaitForChild("GraphicsQuality"))
local KillstreakHUD = require(script.Parent:WaitForChild("KillstreakHUD"))
local TouchControls = require(script.Parent:WaitForChild("TouchControls"))
local LevelBadge = require(script.Parent:WaitForChild("LevelBadge"))
local HubWheel = require(script.Parent:WaitForChild("HubWheel"))
local MarketClient = require(script.Parent:WaitForChild("MarketClient"))
local TradeClient = require(script.Parent:WaitForChild("TradeClient"))
local CrateClient = require(script.Parent:WaitForChild("CrateClient"))
local ExtinctionClient = require(script.Parent:WaitForChild("ExtinctionClient"))

InputActions.Init() -- zuerst: alle anderen Module melden ihre Aktionen hier an
PlayerSettings.Init() -- gespeicherte Einstellungen laden (Movement, HUD usw. hören auf Änderungen)
Movement.Init()
WeaponClient.Init()
CharacterPose.Init() -- Third-Person: Waffe mit beiden Händen bei allen Charakteren
HUD.Init(WeaponClient)
Notifications.Init() -- Medaillen, Runden-Banner, Ziel-, Level- und Belohnungs-Meldungen im CoD-Stil
GameMenu.Init()
AbilityClient.Init()
Glide.Init()
Spectator.Init()
AgentSelect.Init()
SideMenu.Init()
Scoreboard.Init()
Downed.Init()
ObjectivePrompt.Init()
Pings.Init()
MatchSummary.Init()
HubLineup.Init()
Nametags.Init()
MapVote.Init()
MapAtmosphere.Init() -- Lichtstimmung je Map (Weltraum, Tropen)
GraphicsQuality.Init() -- Einstellung Grafik (Schatten, Partikel, Leuchten)
KillstreakHUD.Init() -- Killstreaks in Herrschaft rechts am Rand (Tasten 4/5/6)
TouchControls.Init()
LevelBadge.Init() -- Spielerlevel immer sichtbar (außer in Menüs)
task.spawn(HubWheel.Init) -- Glücksrad in der Ecke des Hubs (wartet auf die Hub-Map)
task.spawn(MarketClient.Init) -- Markthalle: Stände, MEIN STAND, kaufen (wartet auf die Markt-Map)
TradeClient.Init() -- Tauschen im Hub und im Markt (G an anderen Spielern)
task.spawn(CrateClient.Init) -- Kisten öffnen: Automaten in der Marktmitte (Waffen-Kiste, Agenten-Kiste)
ExtinctionClient.Init() -- offene Welt: Hotbar 1-9, Inventar (TAB), Stände, Lager, Taschen, Safe Zone
task.spawn(AdminPanel.Init) -- wartet, bis der Server meldet, ob man Admin ist
